import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/app/store/provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full bg-purple-100">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
